### ISSUE TITLE
bug at the launch of the tutorial... from Windows. MS edge browser

### ISSUE THREAD

**Issue by bjauffret** [labelflow/labelflow#415] opened 2021-09-02 12:58 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by crubier** [comment] 2021-09-08 22:01
We will need more info about this. Do you have a screenshot, or at least a description of the problem you saw ?

**Comment by nicOwlas** [comment] 2021-09-09 10:18
@bjauffret would you have more info? What was the edge version and do could you share a screenshot of your issue?
Hugo can try to test on his old windows machine to see if he can reproduce with latest Edge version.

**Comment by RaynalHugo** [comment] 2021-09-09 12:47
![LabelFlow on MS Edge](https://user-images.githubusercontent.com/2271940/132688343-ffbfd3da-231d-432f-9cc4-ff10dcf17897.jpg)
![Edge version](https://user-images.githubusercontent.com/2271940/132688358-dc592d24-58f4-43a9-883a-4f7cb3505019.jpg)

I couldn't reproduce this issue :/

**Comment by nicOwlas** [comment] 2021-09-09 13:15
Ok thanks @RaynalHugo ! I'll close it for now then.

**Closed by nicOwlas** 2021-09-09 13:15 UTC
Labels: bug, A-eng ready
