### ISSUE TITLE
Online workspaces bugs before release

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#579] opened 2021-11-15 10:24 UTC
## Describe the bug
Online workspaces bugs before release

## Must have

- [x] Edit: Works correctly after creating a new workspace ~~Workspace settings page is not loading. `getWorkspaceDetails ` returns :~~
```
{"errors":[{"message":"Couldn't retrieve Stripe Customer Portal Url of \"nicolas-draber\" as this workspace doesn't have a Stripe Customer Id.","locations":[{"line":8,"column":5}],"path":["workspace","stripeCustomerPortalUrl"]}],"data":{"workspace":{"id":"1fcb9795-6152-4d56-b525-308e71de2b48","plan":"Community","slug":"nicolas-draber","image":null,"name":"nicolas draber","stripeCustomerPortalUrl":null,"__typename":"Workspace"}}}
```
![Screenshot 2021-11-15 at 11 17 09](https://user-images.githubusercontent.com/16015322/141764264-9c1f645c-1aba-4e09-81b6-0f7907de88cd.png)

## Nice to have

- [x] Invitation join your team has no picture
![Screenshot 2021-11-15 at 11 15 06](https://user-images.githubusercontent.com/16015322/141763942-9e12886f-5699-4e7c-883b-dec1716451f8.png)

- [x] Creation of classes and labels is slow: optimistic response?
- [x] Update labelClass is slow
- [x] Invitation join your team link `View online version` is broken
```
http://api/email/view?inviterEmail=nicolas.draber%40labelflow.ai&inviterName=Nicolas%20Draber&origin=&type=invitation&url=%2Fnicolas-draber%2Faccept-invite%3FmembershipId%3Da58eaf13-8a00-4d02-90d1-8c2b0e2c99cc&workspaceName=nicolas%20draber
```
![Screenshot 2021-11-15 at 11 15 47](https://user-images.githubusercontent.com/16015322/141764050-1d5d47cc-02f4-4383-b98a-e9a2c27f700a.png)

**Comment by RaynalHugo** [comment] 2021-11-15 10:32
@nicOwlas 
Regarding the must-have part.
By any chance, did you just create this workspace? Or was it an already existing one?
It works on my side. My guess is that this workspace was created before the Stripe PR was merged and I didn't perform a migration of existing workspaces. Anyway, we will reset the DB before releasing the feature so this problem won't arrive in prod.

**Comment by RaynalHugo** [comment] 2021-11-15 16:47
The broken invitation link and the picture not showing were both caused by an incorrect env var.
If you try to check locally, the email sent won't have working images either. I guess Gmail does its magic and prevents us from loading directly from localhost:3000. It should however work from the deployed branch after the fix.

**Closed** 2021-11-24 11:20 UTC
Labels: bug
