### ISSUE TITLE
Error initiating!

### ISSUE THREAD

**Issue by nunoedgarhubsoftphotoflow** [labelflow/labelflow#754] opened 2022-01-07 12:53 UTC
## To Reproduce

1. 
2. 
3. 
4. 

## Device information

 

- **Device:** 
- **OS:** 
- **Browser:** 
- **Version:**

**Comment by nicOwlas** [comment] 2022-01-07 13:22
Hi @nunoedgarhubsoftphotoflow!
Could you tell us more about the browser you are using (incognito mode or normal) and what error you faced?

**Comment by nicOwlas** [comment] 2022-01-11 10:30
Closing as we cannot reproduce.

**Closed by nicOwlas** 2022-01-11 10:30 UTC
Labels: bug
